name: CI

on:
  push:
    branches: 
     - main
     - jr/actions-project-build
  pull_request:
    branches: [ "main"  ]

jobs:

  Linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10.6' 
     - name: Get latest CMake
       uses: lukka/get-cmake@latest
     - name: Installing Jinja2
       run: python -m pip install Jinja2
     - name: Installing pytest
       run: python -m pip install pytest
     - name: Clone PENE
       run: |
         cd pene_files
         git clone git@github.com:aneoconsulting/PENE.git
     - name: Rubnning cmake
       run: |
         ls ${{github.workspace}}
         mkdir build
         cd build
         cmake .. -DBUILD_FOR_PENE=ON
     - name: Build Solution (Linux)
       run: |
         cd build
         make
